services:

  postgres:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db

  postgres_test:
    image: postgres:15-alpine
    env_file: .env
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres_test
      - POSTGRES_DB=test_db

  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8080:8080"
    command: /usr/local/bin/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db
    restart: on-failure:1

  test:
    build:
      context: .
    depends_on:
      - postgres_test
    env_file: .env
    command: go test -v ./internal/service
    environment:
      - INIT_ENV=test
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres_test
      - POSTGRES_DB=test_db
    restart: on-failure:1

volumes:
  postgres_data: