services:
  postgres:
    env_file: .env
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8080:8080"
    command: /usr/local/bin/app

volumes:
  postgres_data: