version: '3.8'

services:
  postgres:
    env_file: .env_test
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file: .env_test
    command: /usr/local/bin/app
    networks:
      - test_network
    ports:
      - "8080:8080"

  test:
    image: golang:1.19
    working_dir: /app
    command: go test -v internal/service/transfer_test.go
    depends_on:
      - app
      - postgres
    volumes:
      - .:/app
    networks:
      - test_network

volumes:
  postgres_data:

networks:
  test_network:
    driver: bridge