services:

  postgres:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db

  postgres_test:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres_test
      - POSTGRES_DB=test_db

  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8080:8080"
    command: /usr/local/bin/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db
    restart: on-failure:1

  test:
    build:
      context: .
    depends_on:
      - postgres_test
    env_file: .env
    command: "go test -v internal/service/transfer_test.go"
    environment:
      - INIT_ENV=test
      - POSTGRES_HOST=postgres_test
      - POSTGRES_DB=test_db
    restart: on-failure:1

volumes:
  postgres_data: